# Generated by Django 3.2.6 on 2022-10-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('station_id', models.CharField(max_length=10)),
                ('station_name', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=15, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(default=' ', max_length=100)),
                ('contact', models.CharField(default='079-', max_length=12)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
