# Generated by Django 3.2.6 on 2022-10-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_stationmodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationmodel',
            old_name='subdivision',
            new_name='division',
        ),
    ]
