<<<<<<< HEAD
# Generated by Django 3.2.6 on 2022-10-05 07:04
=======
# Generated by Django 3.2.6 on 2022-10-05 15:34
>>>>>>> 9eb0135a1809d0d9397424f0f96c94b219cb4411

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('feedback', '0002_auto_20221005_1227'),
=======
        ('feedback', '0002_auto_20221004_1953'),
>>>>>>> 9eb0135a1809d0d9397424f0f96c94b219cb4411
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='station_id',
            field=models.CharField(max_length=10),
        ),
    ]
